### ISSUE TITLE
Incompatible with PyCharm 2022.3

### ISSUE THREAD

**Issue by allanlewis** [fan-tom/intellij-codeowners#139]
I'm using PyCharm Pro and just upgraded to v2022.3. This plugin is now reported as incompatible; the build number has increased from 222 to 223.

**Comment by fpenovi** [comment]
Experiencing the same with Webstorm

**Comment by fan-tom** [comment]
Fixed in ad75ee396663beafa345d5a9ea51bc72b15a3941
