### ISSUE TITLE
Please support version 2024.2

### ISSUE THREAD

**Issue by ilanKeshet** [fan-tom/intellij-codeowners#280]
Version 0.8.0 is incompatible with 2042.2 

Apparently JetBrains have made some breaking api changes  https://plugins.jetbrains.com/docs/intellij/api-changes-list-2024.html but in my quick search through the code I haven't been able to find any of the kotlin related changes 

`Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2)`
<img width="1516" alt="image" src="https://github.com/user-attachments/assets/8340d519-70a0-440e-88f3-03b4980f2c91">
<img width="678" alt="image" src="https://github.com/user-attachments/assets/70419fa0-14e5-4149-94f7-99452cd77cea">

Thank you very much 🙏

**Comment by chananelsuter** [comment]
+1

**Comment by m-lautenbach** [comment]
+1

**Comment by sarunas-davalga-vinted** [comment]
+1

**Comment by ilanKeshet** [comment]
Thank you @fan-tom Works perfectly
