### ISSUE TITLE
Support docs/ as file location

### ISSUE THREAD

**Issue by bjornbak** [fan-tom/intellij-codeowners#45]
According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location the CODEOWNERS file is allowed in the repo root, docs/ and .github/ but when I have the file in docs/ the plugin doesn't recognize it.

Please add support for docs/ and .github/

**Comment by fan-tom** [comment]
Will implement in the next release
